version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:12.8
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: xambraboookstore
    ports:
      - '5432:5432'